export const enuguNorthElectoralData: Ward[] = [
  // ============================================================
  // WARD 01 — ASATA TOWNSHIP
  // ============================================================

  {
    id: "enugu-north-ward-01",
    code: "01",
    name: "ASATA TOWNSHIP",
    pollingUnits: [
      { id: "enugu-north-ward-01-pu-001", code: "001", name: "UDI ROAD PRIMARY SCHOOL I" },
      { id: "enugu-north-ward-01-pu-002", code: "002", name: "UDI ROAD PRIMARY SCHOOL II" },
      { id: "enugu-north-ward-01-pu-003", code: "003", name: "UDI ROAD PRIMARY SCHOOL III" },
      { id: "enugu-north-ward-01-pu-004", code: "004", name: "UDI ROAD PRIMARY SCHOOL IV" },
      { id: "enugu-north-ward-01-pu-005", code: "005", name: "UDI ROAD PRIMARY SCHOOL V" },
      { id: "enugu-north-ward-01-pu-006", code: "006", name: "UDI ROAD PRIMARY SCHOOL VI" },
      { id: "enugu-north-ward-01-pu-007", code: "007", name: "UDI ROAD PRIMARY SCHOOL VII" },
      { id: "enugu-north-ward-01-pu-008", code: "008", name: "ASATA PRIMARY SCHOOL V" },
      { id: "enugu-north-ward-01-pu-009", code: "009", name: "O’CONOR PRIMARY SCHOOL I" },
      { id: "enugu-north-ward-01-pu-010", code: "010", name: "O’CONOR PRIMARY SCHOOL II" },
      { id: "enugu-north-ward-01-pu-011", code: "011", name: "O’CONOR PRIMARY SCHOOL III" },
      { id: "enugu-north-ward-01-pu-012", code: "012", name: "O’CONOR PRIMARY SCHOOL IV" },
      { id: "enugu-north-ward-01-pu-013", code: "013", name: "O’CONOR PRIMARY SCHOOL V" },
      { id: "enugu-north-ward-01-pu-014", code: "014", name: "O’CONOR PRIMARY SCHOOL VI" },
      { id: "enugu-north-ward-01-pu-015", code: "015", name: "ASATA PRIMARY SCHOOL I" },
      { id: "enugu-north-ward-01-pu-016", code: "016", name: "ASATA PRIMARY SCHOOL II" },
      { id: "enugu-north-ward-01-pu-017", code: "017", name: "ASATA PRIMARY SCHOOL III" },
      { id: "enugu-north-ward-01-pu-018", code: "018", name: "ASATA PRIMARY SCHOOL IV" },
      { id: "enugu-north-ward-01-pu-019", code: "019", name: "OWERRI ROAD SUYA SPOT" },
      { id: "enugu-north-ward-01-pu-020", code: "020", name: "NZEKWE PLAYGROUND I" },
      { id: "enugu-north-ward-01-pu-021", code: "021", name: "NZEKWE PLAYGROUND II" },
      { id: "enugu-north-ward-01-pu-022", code: "022", name: "ENUGU STADIUM" },
      { id: "enugu-north-ward-01-pu-023", code: "023", name: "NIPOST WAREHOUSE I" },
      { id: "enugu-north-ward-01-pu-024", code: "024", name: "NIPOST WAREHOUSE II" },
      { id: "enugu-north-ward-01-pu-025", code: "025", name: "RICHARD STREET PRIMARY SCHOOL I" },
      { id: "enugu-north-ward-01-pu-026", code: "026", name: "RICHARD STREET PRIMARY SCHOOL II" },
      { id: "enugu-north-ward-01-pu-027", code: "027", name: "RICHARD STREET PRIMARY SCHOOL III" },
      { id: "enugu-north-ward-01-pu-028", code: "028", name: "RICHARD STREET PRIMARY SCHOOL IV" },
    ],
  },

  // ============================================================
  // WARD 02 — UMUNEVO
  // ============================================================

  {
    id: "enugu-north-ward-02",
    code: "02",
    name: "UMUNEVO",
    pollingUnits: [
      { id: "enugu-north-ward-02-pu-001", code: "001", name: "AFIA NINE V/SQUARE I" },
      { id: "enugu-north-ward-02-pu-002", code: "002", name: "AFIA NINE V/SQUARE II" },
      { id: "enugu-north-ward-02-pu-003", code: "003", name: "AFIA NINE V/SQUARE III" },
      { id: "enugu-north-ward-02-pu-004", code: "004", name: "AFIA NINE V/SQUARE IV" },
      { id: "enugu-north-ward-02-pu-005", code: "005", name: "AFIA NINE V/SQUARE V" },
      { id: "enugu-north-ward-02-pu-006", code: "006", name: "AFIA NINE V/SQUARE VI" },
      { id: "enugu-north-ward-02-pu-007", code: "007", name: "AFIA NINE V/SQUARE VII" },
      { id: "enugu-north-ward-02-pu-008", code: "008", name: "AFIA NINE V/SQUARE VIII" },
      { id: "enugu-north-ward-02-pu-009", code: "009", name: "ESUT (FORMER CITY GIRLS’) I" },
      { id: "enugu-north-ward-02-pu-010", code: "010", name: "ESUT (FORMER CITY GIRLS’) II" },
      { id: "enugu-north-ward-02-pu-011", code: "011", name: "ESUT (FORMER CITY GIRLS’) III" },
      { id: "enugu-north-ward-02-pu-012", code: "012", name: "ESUT (FORMER CITY GIRLS’) IV" },
      { id: "enugu-north-ward-02-pu-013", code: "013", name: "ESUT (FORMER CITY GIRLS’) V" },
      { id: "enugu-north-ward-02-pu-014", code: "014", name: "AFIA NINE V/SQUARE IX" },
      { id: "enugu-north-ward-02-pu-015", code: "015", name: "ESUT (FORMER CITY GIRLS) VI" },
      { id: "enugu-north-ward-02-pu-016", code: "016", name: "ESUT (FORMER CITY GIRLS) VII" },
      { id: "enugu-north-ward-02-pu-017", code: "017", name: "UMUNEVO OGUI NIKE- AFIA NINE EXTENSION I" },
      { id: "enugu-north-ward-02-pu-018", code: "018", name: "UMUNEVO OGUI NIKE- AFIA NINE EXTENSION II" },
      { id: "enugu-north-ward-02-pu-019", code: "019", name: "UMUNEVO OGUI NIKE- AFIA NINE EXTENSION III" },
      { id: "enugu-north-ward-02-pu-020", code: "020", name: "UMUNEVO OGUI NIKE- AFIA NINE EXTENSION IV" },
    ],
  },

  // ============================================================
  // WARD 03 — IHEWUZI
  // ============================================================

  {
    id: "enugu-north-ward-03",
    code: "03",
    name: "IHEWUZI",
    pollingUnits: [
      { id: "enugu-north-ward-03-pu-001", code: "001", name: "IHEWUZI SQUARE I" },
      { id: "enugu-north-ward-03-pu-002", code: "002", name: "IHEWUZI SQUARE II" },
      { id: "enugu-north-ward-03-pu-003", code: "003", name: "IHEWUZI SQUARE III" },
      { id: "enugu-north-ward-03-pu-004", code: "004", name: "IHEWUZI SQUARE IV" },
      { id: "enugu-north-ward-03-pu-005", code: "005", name: "IHEWUZI SQUARE V" },
      { id: "enugu-north-ward-03-pu-006", code: "006", name: "ONUATOR SQUARE" },
      { id: "enugu-north-ward-03-pu-007", code: "007", name: "IHEWUZI SQUARE VI" },
      { id: "enugu-north-ward-03-pu-008", code: "008", name: "IHEWUZI SQUARE VII" },
      { id: "enugu-north-ward-03-pu-009", code: "009", name: "IHEWUZI SQUARE IX" },
      { id: "enugu-north-ward-03-pu-010", code: "010", name: "IHEWUZI SQUARE X" },
      { id: "enugu-north-ward-03-pu-011", code: "011", name: "IHEWUZI GROUND I" },
      { id: "enugu-north-ward-03-pu-012", code: "012", name: "IHEWUZI GROUND II" },
      { id: "enugu-north-ward-03-pu-013", code: "013", name: "ISHIAGU ONUATO SQUARE I" },
      { id: "enugu-north-ward-03-pu-014", code: "014", name: "ISHIAGU ONUATO SQUARE II" },
    ],
  },

  // ============================================================
  // WARD 04 — ONU-ASATA
  // ============================================================

  {
    id: "enugu-north-ward-04",
    code: "04",
    name: "ONU-ASATA",
    pollingUnits: [
      { id: "enugu-north-ward-04-pu-001", code: "001", name: "OGUI NIKE PRIMARY SCHOOL (ST. LUKE’S) I" },
      { id: "enugu-north-ward-04-pu-002", code: "002", name: "OGUI NIKE PRIMARY SCHOOL (ST. LUKE’S) II" },
      { id: "enugu-north-ward-04-pu-003", code: "003", name: "OGUI NIKE PRIMARY SCHOOL (ST. LUKE’S) III" },
      { id: "enugu-north-ward-04-pu-004", code: "004", name: "OGUI NIKE PRIMARY SCHOOL (ST. LUKE’S) IV" },
      { id: "enugu-north-ward-04-pu-005", code: "005", name: "OGUI NIKE PRIMARY SCHOOL (ST. LUKE’S) V" },
      { id: "enugu-north-ward-04-pu-006", code: "006", name: "OGUI NIKE PRIMARY SCHOOL (ST. LUKE’S) VI" },
      { id: "enugu-north-ward-04-pu-007", code: "007", name: "OGUI NIKE PRIMARY SCHOOL (ST. LUKE’S) VII" },
      { id: "enugu-north-ward-04-pu-008", code: "008", name: "OGUI NIKE PRIMARY SCHOOL (ST. LUKE’S) VIII" },
      { id: "enugu-north-ward-04-pu-009", code: "009", name: "OGUI NIKE PRIMARY SCHOOL (ST. LUKE’S) IX" },
      { id: "enugu-north-ward-04-pu-010", code: "010", name: "OGUI/ULI AVENUE I" },
      { id: "enugu-north-ward-04-pu-011", code: "011", name: "OGUI/ULI AVENUE II" },
      { id: "enugu-north-ward-04-pu-012", code: "012", name: "OGUI/ULI AVENUE III" },
      { id: "enugu-north-ward-04-pu-013", code: "013", name: "OGUI/ULI AVENUE IV" },
      { id: "enugu-north-ward-04-pu-014", code: "014", name: "OGUI/ULI AVENUE V" },
      { id: "enugu-north-ward-04-pu-015", code: "015", name: "OGUI/ULI AVENUE VI" },
      { id: "enugu-north-ward-04-pu-016", code: "016", name: "OGUI/ULI AVENUE VII" },
    ],
  },

  // ============================================================
  // WARD 05 — OGBETTE EAST
  // ============================================================

  {
    id: "enugu-north-ward-05",
    code: "05",
    name: "OGBETTE EAST",
    pollingUnits: [
      { id: "enugu-north-ward-05-pu-001", code: "001", name: "COLLIERY PLAY GROUND I" },
      { id: "enugu-north-ward-05-pu-002", code: "002", name: "COLLIERY PLAY GROUND II" },
      { id: "enugu-north-ward-05-pu-003", code: "003", name: "COLLIERY PLAY GROUND III" },
      { id: "enugu-north-ward-05-pu-004", code: "004", name: "ST. PETER’S PRIMARY SCHOOL I" },
      { id: "enugu-north-ward-05-pu-005", code: "005", name: "ST. PETER’S PRIMARY SCHOOL II" },
      { id: "enugu-north-ward-05-pu-006", code: "006", name: "ST. PETER’S PRIMARY SCHOOL III" },
      { id: "enugu-north-ward-05-pu-007", code: "007", name: "ST. PATRICK’S PRIMARY SCHOOL I" },
      { id: "enugu-north-ward-05-pu-008", code: "008", name: "ST. PATRICK’S PRIMARY SCHOOL II" },
      { id: "enugu-north-ward-05-pu-009", code: "009", name: "ST. PATRICK’S PRIMARY SCHOOL III" },
      { id: "enugu-north-ward-05-pu-010", code: "010", name: "EJINDU PARK I" },
      { id: "enugu-north-ward-05-pu-011", code: "011", name: "EJINDU PARK II" },
      { id: "enugu-north-ward-05-pu-012", code: "012", name: "EJINDU PARK III" },
      { id: "enugu-north-ward-05-pu-013", code: "013", name: "EJINDU PARK IV" },
      { id: "enugu-north-ward-05-pu-014", code: "014", name: "OBED CAMP I" },
      { id: "enugu-north-ward-05-pu-015", code: "015", name: "OBED CAMP II" },
      { id: "enugu-north-ward-05-pu-016", code: "016", name: "OBED CAMP III" },
      { id: "enugu-north-ward-05-pu-017", code: "017", name: "EJINDU PARK V" },
      { id: "enugu-north-ward-05-pu-018", code: "018", name: "COLLIERY HALL IV" },
      { id: "enugu-north-ward-05-pu-019", code: "019", name: "ST. PATRICK’S PRIMARY SCHOOL IV" },
      { id: "enugu-north-ward-05-pu-020", code: "020", name: "EJINDU PARK VI" },
      { id: "enugu-north-ward-05-pu-021", code: "021", name: "MECHANIC VILLAGE, OPP. ST. PATRICK’S COLLEGE I" },
      { id: "enugu-north-ward-05-pu-022", code: "022", name: "MECHANIC VILLAGE, OPP. ST. PATRICK’S COLLEGE II" },
      { id: "enugu-north-ward-05-pu-023", code: "023", name: "COAL CAMP POST OFFICE I" },
      { id: "enugu-north-ward-05-pu-024", code: "024", name: "COAL CAMP POST OFFICE II" },
      { id: "enugu-north-ward-05-pu-025", code: "025", name: "COAL CAMP POST OFFICE III" },
    ],
  },

  // ============================================================
  // WARD 06 — OGBETTE WEST
  // ============================================================

  {
    id: "enugu-north-ward-06",
    code: "06",
    name: "OGBETTE WEST",
    pollingUnits: [
      { id: "enugu-north-ward-06-pu-001", code: "001", name: "BROADRICK PRIMARY SCHOOL I" },
      { id: "enugu-north-ward-06-pu-002", code: "002", name: "BROADRICK PRIMARY SCHOOL II" },
      { id: "enugu-north-ward-06-pu-003", code: "003", name: "BROADRICK PRIMARY SCHOOL III" },
      { id: "enugu-north-ward-06-pu-004", code: "004", name: "BROADRICK PRIMARY SCHOOL IV" },
      { id: "enugu-north-ward-06-pu-005", code: "005", name: "BROADRICK PRIMARY SCHOOL V" },
      { id: "enugu-north-ward-06-pu-006", code: "006", name: "BROADRICK PRIMARY SCHOOL VI" },
      { id: "enugu-north-ward-06-pu-007", code: "007", name: "BROADRICK PRIMARY SCHOOL VII" },
      { id: "enugu-north-ward-06-pu-008", code: "008", name: "SPECIAL EDUCATION CENTRE I" },
      { id: "enugu-north-ward-06-pu-009", code: "009", name: "SPECIAL EDUCATION CENTRE II" },
      { id: "enugu-north-ward-06-pu-010", code: "010", name: "SPECIAL EDUCATION CENTRE III" },
      { id: "enugu-north-ward-06-pu-011", code: "011", name: "SPECIAL EDUCATION CENTRE IV" },
      { id: "enugu-north-ward-06-pu-012", code: "012", name: "SPECIAL EDUCATION CENTRE V" },
      { id: "enugu-north-ward-06-pu-013", code: "013", name: "OGBETTE PRIMARY SCHOOL I" },
      { id: "enugu-north-ward-06-pu-014", code: "014", name: "OGBETTE PRIMARY SCHOOL II" },
      { id: "enugu-north-ward-06-pu-015", code: "015", name: "OGBETTE PRIMARY SCHOOL III" },
      { id: "enugu-north-ward-06-pu-016", code: "016", name: "OGBETTE PRIMARY SCHOOL IV" },
      { id: "enugu-north-ward-06-pu-017", code: "017", name: "OGBETTE PRIMARY SCHOOL V" },
      { id: "enugu-north-ward-06-pu-018", code: "018", name: "OGBETTE PRIMARY SCHOOL VI" },
      { id: "enugu-north-ward-06-pu-019", code: "019", name: "EJAGU SQUARE I" },
      { id: "enugu-north-ward-06-pu-020", code: "020", name: "EJAGU SQUARE II" },
      { id: "enugu-north-ward-06-pu-021", code: "021", name: "EJAGU SQUARE III" },
      { id: "enugu-north-ward-06-pu-022", code: "022", name: "EJAGU SQUARE IV" },
      { id: "enugu-north-ward-06-pu-023", code: "023", name: "CITY PRIMARY SCHOOL, OGBETE I" },
      { id: "enugu-north-ward-06-pu-024", code: "024", name: "CITY PRIMARY SCHOOL, OGBETE II" },
      { id: "enugu-north-ward-06-pu-025", code: "025", name: "CITY PRIMARY SCHOOL, OGBETE III" },
      { id: "enugu-north-ward-06-pu-026", code: "026", name: "CITY PRIMARY SCHOOL, OGBETE IV" },
      { id: "enugu-north-ward-06-pu-027", code: "027", name: "FED. MIN. OF WATER RESOURCES I" },
      { id: "enugu-north-ward-06-pu-028", code: "028", name: "FED. MIN. OF WATER RESOURCES II" },
      { id: "enugu-north-ward-06-pu-029", code: "029", name: "FED. MIN. OF WATER RESOURCES III" },
    ],
  },

  // ============================================================
  // WARD 07 — G.R.A
  // ============================================================

  {
    id: "enugu-north-ward-07",
    code: "07",
    name: "G.R.A",
    pollingUnits: [
      { id: "enugu-north-ward-07-pu-001", code: "001", name: "EKULU PRIMARY SCHOOL I" },
      { id: "enugu-north-ward-07-pu-002", code: "002", name: "EKULU PRIMARY SCHOOL II" },
      { id: "enugu-north-ward-07-pu-003", code: "003", name: "EKULU PRIMARY SCHOOL III" },
      { id: "enugu-north-ward-07-pu-004", code: "004", name: "EKULU PRIMARY SCHOOL IV" },
      { id: "enugu-north-ward-07-pu-005", code: "005", name: "POLO PARK I" },
      { id: "enugu-north-ward-07-pu-006", code: "006", name: "POLO PARK II" },
      { id: "enugu-north-ward-07-pu-007", code: "007", name: "POLO PARK III" },
      { id: "enugu-north-ward-07-pu-008", code: "008", name: "POLO PARK IV" },
      { id: "enugu-north-ward-07-pu-009", code: "009", name: "POLO PARK V" },
      { id: "enugu-north-ward-07-pu-010", code: "010", name: "POLO PARK VI" },
      { id: "enugu-north-ward-07-pu-011", code: "011", name: "POLO PARK VII" },
      { id: "enugu-north-ward-07-pu-012", code: "012", name: "POLO PARK VIII" },
      { id: "enugu-north-ward-07-pu-013", code: "013", name: "G.T.C I" },
      { id: "enugu-north-ward-07-pu-014", code: "014", name: "G.T.C II" },
      { id: "enugu-north-ward-07-pu-015", code: "015", name: "EKULU PRIMARY SCHOOL I" },
      { id: "enugu-north-ward-07-pu-016", code: "016", name: "EKULU PRIMARY SCHOOL II" },
      { id: "enugu-north-ward-07-pu-017", code: "017", name: "EKULU PRIMARY SCHOOL III" },
      { id: "enugu-north-ward-07-pu-018", code: "018", name: "EKULU PRIMARY SCHOOL IV" },
      { id: "enugu-north-ward-07-pu-019", code: "019", name: "NATIONAL MUSEUM I" },
      { id: "enugu-north-ward-07-pu-020", code: "020", name: "NATIONAL MUSEUM II" },
      { id: "enugu-north-ward-07-pu-021", code: "021", name: "NATIONAL MUSEUM III" },
      { id: "enugu-north-ward-07-pu-022", code: "022", name: "NATIONAL MUSEUM IV" },
      { id: "enugu-north-ward-07-pu-023", code: "023", name: "NATIONAL MUSEUM V" },
      { id: "enugu-north-ward-07-pu-024", code: "024", name: "NATIONAL MUSEUM VI" },
      { id: "enugu-north-ward-07-pu-025", code: "025", name: "NATIONAL MUSEUM VII" },
      { id: "enugu-north-ward-07-pu-026", code: "026", name: "NATIONAL MUSEUM VIII" },
      { id: "enugu-north-ward-07-pu-027", code: "027", name: "NATIONAL MUSEUM IX" },
      { id: "enugu-north-ward-07-pu-028", code: "028", name: "NATIONAL MUSEUM X" },
      { id: "enugu-north-ward-07-pu-029", code: "029", name: "NATIONAL MUSEUM XI" },
      { id: "enugu-north-ward-07-pu-030", code: "030", name: "ENUGU SPORTS CLUB I" },
      { id: "enugu-north-ward-07-pu-031", code: "031", name: "ENUGU SPORTS CLUB II" },
      { id: "enugu-north-ward-07-pu-032", code: "032", name: "ENUGU SPORTS CLUB III" },
      { id: "enugu-north-ward-07-pu-033", code: "033", name: "ENUGU SPORT CLUB IV" },
      { id: "enugu-north-ward-07-pu-034", code: "034", name: "GOVERNMENT SECONDARY SCHOOL GRA I" },
      { id: "enugu-north-ward-07-pu-035", code: "035", name: "GOVERNMENT SECONDARY SCHOOL GRA II" },
      { id: "enugu-north-ward-07-pu-036", code: "036", name: "GOVERNMENT SECONDARY SCHOOL GRA III" },
      { id: "enugu-north-ward-07-pu-037", code: "037", name: "ENUGU INT. TRADE FAIR I" },
      { id: "enugu-north-ward-07-pu-038", code: "038", name: "ENUGU INTERNATIONAL TRADE FAIR II" },
      { id: "enugu-north-ward-07-pu-039", code: "039", name: "ENUGU INTERNATIONAL TRADE FAIR III" },
      { id: "enugu-north-ward-07-pu-040", code: "040", name: "ENUGU INTERNATIONAL TRADE FAIR IV" },
      { id: "enugu-north-ward-07-pu-041", code: "041", name: "ENUGU INTERNATIONAL TRADE FAIR V" },
    ],
  },

  // ============================================================
  // WARD 08 — GUI NEWLAYOUT
  // ============================================================

  {
    id: "enugu-north-ward-08",
    code: "08",
    name: "GUI NEWLAYOUT",
    pollingUnits: [
      { id: "enugu-north-ward-08-pu-001", code: "001", name: "W.T.C. I" },
      { id: "enugu-north-ward-08-pu-002", code: "002", name: "W.T.C. II" },
      { id: "enugu-north-ward-08-pu-003", code: "003", name: "W.T.C. III" },
      { id: "enugu-north-ward-08-pu-004", code: "004", name: "OBIAGU ROAD PRIMARY SCHOOL I" },
      { id: "enugu-north-ward-08-pu-005", code: "005", name: "OBIAGU ROAD PRIMARY SCHOOL II" },
      { id: "enugu-north-ward-08-pu-006", code: "006", name: "QUEEN’S SCHOOL I" },
      { id: "enugu-north-ward-08-pu-007", code: "007", name: "QUEEN’S SCHOOL II" },
      { id: "enugu-north-ward-08-pu-008", code: "008", name: "QUEEN’S SCHOOL III" },
      { id: "enugu-north-ward-08-pu-009", code: "009", name: "EDINBURGH PRIMARY SCHOOL I" },
      { id: "enugu-north-ward-08-pu-010", code: "010", name: "EDINBURGH PRIMARY SCHOOL II" },
      { id: "enugu-north-ward-08-pu-011", code: "011", name: "ENUGU CAMPUS I" },
      { id: "enugu-north-ward-08-pu-012", code: "012", name: "ENUGU CAMPUS II" },
      { id: "enugu-north-ward-08-pu-013", code: "013", name: "ENUGU CAMPUS III" },
      { id: "enugu-north-ward-08-pu-014", code: "014", name: "ENUGU CAMPUS IV" },
      { id: "enugu-north-ward-08-pu-015", code: "015", name: "EDINBURGH PRIMARY SCHOOL III" },
      { id: "enugu-north-ward-08-pu-016", code: "016", name: "EDINBURGH PRIMARY SCHOOL IV" },
      { id: "enugu-north-ward-08-pu-017", code: "017", name: "UMUNEVO PLAYGROUND OPPOSITE TRANSFORMERS I" },
      { id: "enugu-north-ward-08-pu-018", code: "018", name: "OBIAGU LAST BUS STOP I" },
      { id: "enugu-north-ward-08-pu-019", code: "019", name: "OBIAGU LAST BUS STOP II" },
      { id: "enugu-north-ward-08-pu-020", code: "020", name: "UMUNEVO PLAYGROUND OPPOSITE TRANSFORMERS II" },
      { id: "enugu-north-ward-08-pu-021", code: "021", name: "UNN SEC. SCHOOL, ENUGU CAMPUS I" },
      { id: "enugu-north-ward-08-pu-022", code: "022", name: "UNN SEC. SCHOOL, ENUGU CAMPUS II" },
      { id: "enugu-north-ward-08-pu-023", code: "023", name: "OSADEBE PARK 1" },
      { id: "enugu-north-ward-08-pu-024", code: "024", name: "OSADEBE PARK II" },
      { id: "enugu-north-ward-08-pu-025", code: "025", name: "OSADEBE PARK III" },
      { id: "enugu-north-ward-08-pu-026", code: "026", name: "OSADEBE PARK IV" },
      { id: "enugu-north-ward-08-pu-027", code: "027", name: "OSADEBE PARK V" },
      { id: "enugu-north-ward-08-pu-028", code: "028", name: "OSADEBE PARK VI" },
      { id: "enugu-north-ward-08-pu-029", code: "029", name: "CITY GIRLS COLLEGE 1" },
      { id: "enugu-north-ward-08-pu-030", code: "030", name: "CITY GIRLS COLLEGE II" },
      { id: "enugu-north-ward-08-pu-031", code: "031", name: "CITY GIRLS COLLEGE III" },
      { id: "enugu-north-ward-08-pu-032", code: "032", name: "OBIAGU PLAYGROUND, OPPOSITE COUNCIL TRANSFORMER I" },
      { id: "enugu-north-ward-08-pu-033", code: "033", name: "OBIAGU PLAYGROUND, OPPOSITE COUNCIL TRANSFORMER II" },
      { id: "enugu-north-ward-08-pu-034", code: "034", name: "CITY GIRLS COLLEGE IV" },
      { id: "enugu-north-ward-08-pu-035", code: "035", name: "URBAN GIRL’S SEC. SCHOOL I" },
      { id: "enugu-north-ward-08-pu-036", code: "036", name: "URBAN GIRL’S SEC. SCHOOL II" },
      { id: "enugu-north-ward-08-pu-037", code: "037", name: "URBAN GIRL’S SEC. SCHOOL III" },
      { id: "enugu-north-ward-08-pu-038", code: "038", name: "URBAN GIRL’S SEC. SCHOOL IV" },
    ],
  },

  // ============================================================
  // WARD 09 — CHINA TOWN
  // ============================================================

  {
    id: "enugu-north-ward-09",
    code: "09",
    name: "CHINA TOWN",
    pollingUnits: [
      { id: "enugu-north-ward-09-pu-001", code: "001", name: "CONSTRUCTION PRIMARY SCHOOL I" },
      { id: "enugu-north-ward-09-pu-002", code: "002", name: "CONSTRUCTION PRIMARY SCHOOL II" },
      { id: "enugu-north-ward-09-pu-003", code: "003", name: "CONSTRUCTION PRIMARY SCHOOL III" },
      { id: "enugu-north-ward-09-pu-004", code: "004", name: "CONSTRUCTION PRIMARY SCHOOL IV" },
      { id: "enugu-north-ward-09-pu-005", code: "005", name: "CONSTRUCTION PRIMARY SCHOOL V" },
      { id: "enugu-north-ward-09-pu-006", code: "006", name: "ARTISAN PRIMARY SCHOOL I" },
      { id: "enugu-north-ward-09-pu-007", code: "007", name: "ARTISAN PRIMARY SCHOOL II" },
      { id: "enugu-north-ward-09-pu-008", code: "008", name: "ARTISAN PRIMARY SCHOOL III" },
      { id: "enugu-north-ward-09-pu-009", code: "009", name: "ARTISAN PRIMARY SCHOOL IV" },
      { id: "enugu-north-ward-09-pu-010", code: "010", name: "ARTISAN PRIMARY SCHOOL V" },
      { id: "enugu-north-ward-09-pu-011", code: "011", name: "CHINA TOWN PRIMARY SCHOOL I" },
      { id: "enugu-north-ward-09-pu-012", code: "012", name: "CHINA TOWN PRIMARY SCHOOL II" },
      { id: "enugu-north-ward-09-pu-013", code: "013", name: "CHINA TOWN PRIMARY SCHOOL III" },
      { id: "enugu-north-ward-09-pu-014", code: "014", name: "CHINA TOWN PRIMARY SCHOOL IV" },
      { id: "enugu-north-ward-09-pu-015", code: "015", name: "CONSTRUCTION PRIMARY SCHOOL VI" },
      { id: "enugu-north-ward-09-pu-016", code: "016", name: "CHINA TOWN PRIMARY SCHOOL V" },
      { id: "enugu-north-ward-09-pu-017", code: "017", name: "CHINA TOWN PRIMARY SCHOOL VI" },
      { id: "enugu-north-ward-09-pu-018", code: "018", name: "LICENSING OFFICE, OPP. OLOKO GATE BUS STOP I" },
      { id: "enugu-north-ward-09-pu-019", code: "019", name: "LICENSING OFFICE, OPP. OLOKO GATE BUS STOP II" },
      { id: "enugu-north-ward-09-pu-020", code: "020", name: "LICENSING OFFICE, OPP. OLOKO GATE BUS STOP III" },
      { id: "enugu-north-ward-09-pu-021", code: "021", name: "NJEMANZE RAILWAY ROAD I" },
      { id: "enugu-north-ward-09-pu-022", code: "022", name: "NJEMANZE RAILWAY ROAD II" },
      { id: "enugu-north-ward-09-pu-023", code: "023", name: "OGUI ROAD OTIGBA SQUARE I" },
      { id: "enugu-north-ward-09-pu-024", code: "024", name: "OGUI ROAD OTIGBA SQUARE II" },
      { id: "enugu-north-ward-09-pu-025", code: "025", name: "OGUI ROAD OTIGBA SQUARE III" },
    ],
  },

  // ============================================================
  // WARD 10 — NEW HAVEN
  // ============================================================

  {
    id: "enugu-north-ward-10",
    code: "10",
    name: "NEW HAVEN",
    pollingUnits: [
      { id: "enugu-north-ward-10-pu-001", code: "001", name: "NEW HAVEN PRIMARY SCHOOL I" },
      { id: "enugu-north-ward-10-pu-002", code: "002", name: "NEW HAVEN PRIMARY SCHOOL II" },
      { id: "enugu-north-ward-10-pu-003", code: "003", name: "NEW HAVEN PRIMARY SCHOOL III" },
      { id: "enugu-north-ward-10-pu-004", code: "004", name: "NEW HAVEN PRIMARY SCHOOL IV" },
      { id: "enugu-north-ward-10-pu-005", code: "005", name: "NEW HAVEN PRIMARY SCHOOL V" },
      { id: "enugu-north-ward-10-pu-006", code: "006", name: "NEW HAVEN PRIMARY SCHOOL VI" },
      { id: "enugu-north-ward-10-pu-007", code: "007", name: "NEW HAVEN PRIMARY SCHOOL VII" },
      { id: "enugu-north-ward-10-pu-008", code: "008", name: "C.C.I. (SUYA SPOT) I" },
      { id: "enugu-north-ward-10-pu-009", code: "009", name: "C.C.I. (SUYA SPOT) II" },
      { id: "enugu-north-ward-10-pu-010", code: "010", name: "C.C.I. (SUYA SPOT) III" },
      { id: "enugu-north-ward-10-pu-011", code: "011", name: "C.C.I. (SUYA SPOT) IV" },
      { id: "enugu-north-ward-10-pu-012", code: "012", name: "C.C.I. (SUYA SPOT) V" },
      { id: "enugu-north-ward-10-pu-013", code: "013", name: "C.C.I. (SUYA SPOT) VI" },
      { id: "enugu-north-ward-10-pu-014", code: "014", name: "C.C.I. (SUYA SPOT) VII" },
      { id: "enugu-north-ward-10-pu-015", code: "015", name: "C.C.I. (SUYA SPOT) VIII" },
      { id: "enugu-north-ward-10-pu-016", code: "016", name: "UGBO OKONKWO SQUARE I" },
      { id: "enugu-north-ward-10-pu-017", code: "017", name: "UGBO OKONKWO SQUARE II" },
      { id: "enugu-north-ward-10-pu-018", code: "018", name: "N.E.P.A. QUARTERS (NEAR VOM NURSERY)" },
      { id: "enugu-north-ward-10-pu-019", code: "019", name: "CAR WASH SPOT NZA ST. LINK ROAD I" },
      { id: "enugu-north-ward-10-pu-020", code: "020", name: "CAR WASH SPOT NZA ST LINK II" },
      { id: "enugu-north-ward-10-pu-021", code: "021", name: "CHIEF EDWARD NNAJI PARK I" },
      { id: "enugu-north-ward-10-pu-022", code: "022", name: "CHIEF EDWARD NNAJI PARK II" },
      { id: "enugu-north-ward-10-pu-023", code: "023", name: "CHIEF EDWARD NNAJI PARK III" },
      { id: "enugu-north-ward-10-pu-024", code: "024", name: "CHIEF EDWARD NNAJI PARK IV" },
      { id: "enugu-north-ward-10-pu-025", code: "025", name: "CHIEF EDWARD NNAJI PARK V" },
      { id: "enugu-north-ward-10-pu-026", code: "026", name: "NEW HAVEN HEALTH CENTRE I" },
      { id: "enugu-north-ward-10-pu-027", code: "027", name: "NEW HAVEN HEALTH CENTRE II" },
      { id: "enugu-north-ward-10-pu-028", code: "028", name: "NEW HAVEN HEALTH CENTRE III" },
      { id: "enugu-north-ward-10-pu-029", code: "029", name: "COMPUTER VILLAGE/FIRE SERVICE I" },
      { id: "enugu-north-ward-10-pu-030", code: "030", name: "COMPUTER VILLAGE/FIRE SERVICE II" },
      { id: "enugu-north-ward-10-pu-031", code: "031", name: "COMPUTER VILLAGE/FIRE SERVICE III" },
      { id: "enugu-north-ward-10-pu-032", code: "032", name: "UMUEZEBI COMM. HALL (DANNIC AVE I)" },
      { id: "enugu-north-ward-10-pu-033", code: "033", name: "UMUEZEBI COMM. HALL (DANNIC AVE II)" },
      { id: "enugu-north-ward-10-pu-034", code: "034", name: "UMUEZEBI COMM. HALL (DANNIC AVE III)" },
      { id: "enugu-north-ward-10-pu-035", code: "035", name: "UMUEZEBI COMM. HALL (DANNIC AVE IV)" },
      { id: "enugu-north-ward-10-pu-036", code: "036", name: "NEW HAVEN SEC. SCHOOL I" },
      { id: "enugu-north-ward-10-pu-037", code: "037", name: "NEW HAVEN SEC. SCHOOL II" },
    ],
  },

  // ============================================================
  // WARD 11 — INDEPENDENCE LAYOUT
  // ============================================================

  {
    id: "enugu-north-ward-11",
    code: "11",
    name: "INDEPENDENCE LAYOUT",
    pollingUnits: [
      { id: "enugu-north-ward-11-pu-001", code: "001", name: "FORMER N.A.F. NURSERY SCHOOL I" },
      { id: "enugu-north-ward-11-pu-002", code: "002", name: "FORMER N.A.F. NURSERY SCHOOL II" },
      { id: "enugu-north-ward-11-pu-003", code: "003", name: "OKPARA SQUARE I" },
      { id: "enugu-north-ward-11-pu-004", code: "004", name: "OKPARA SQUARE II" },
      { id: "enugu-north-ward-11-pu-005", code: "005", name: "OKPARA SQUARE III" },
      { id: "enugu-north-ward-11-pu-006", code: "006", name: "OKPARA SQUARE IV" },
      { id: "enugu-north-ward-11-pu-007", code: "007", name: "OKPARA SQUARE V" },
      { id: "enugu-north-ward-11-pu-008", code: "008", name: "OKPARA SQUARE VI" },
      { id: "enugu-north-ward-11-pu-009", code: "009", name: "FEDERAL GOVERNMENT SCHOOL I" },
      { id: "enugu-north-ward-11-pu-010", code: "010", name: "FEDERAL GOVERNMENT SCHOOL II" },
      { id: "enugu-north-ward-11-pu-011", code: "011", name: "I.M.T. CAMPUS I" },
      { id: "enugu-north-ward-11-pu-012", code: "012", name: "I.M.T. CAMPUS II" },
      { id: "enugu-north-ward-11-pu-013", code: "013", name: "FEDERAL GOVERNMENT SCHOOL III" },
      { id: "enugu-north-ward-11-pu-014", code: "014", name: "NZA ST. SQUARE" },
      { id: "enugu-north-ward-11-pu-015", code: "015", name: "NZA ST. SQUARE" },
      { id: "enugu-north-ward-11-pu-016", code: "016", name: "NZA STR. SQUARE" },
      { id: "enugu-north-ward-11-pu-017", code: "017", name: "NZA STR. SQUARE" },
      { id: "enugu-north-ward-11-pu-018", code: "018", name: "NZA STR. SQUARE" },
      { id: "enugu-north-ward-11-pu-019", code: "019", name: "NIG. AIRPORT AUTHORITY, NZA STR." },
      { id: "enugu-north-ward-11-pu-020", code: "020", name: "NIG. AIRPORT AUTHORITY, NZA STR." },
      { id: "enugu-north-ward-11-pu-021", code: "021", name: "EZIKWO CAR WASH, ROBAN ROAD" },
      { id: "enugu-north-ward-11-pu-022", code: "022", name: "INDEPENDENCE LAYOUT SECONDARY SCHOOL I" },
      { id: "enugu-north-ward-11-pu-023", code: "023", name: "INDEPENDENCE LAYOUT SECONDARY SCHOOL II" },
      { id: "enugu-north-ward-11-pu-024", code: "024", name: "INDEPENDENCE LAYOUT – BRICKS" },
      { id: "enugu-north-ward-11-pu-025", code: "025", name: "INDEPENDENCE LAYOUT – BRICKS II)" },
      { id: "enugu-north-ward-11-pu-026", code: "026", name: "INDEPENDENCE LAYOUT BRICKS III" },
      { id: "enugu-north-ward-11-pu-027", code: "027", name: "CUSTOM/HANSA AVENUE I" },
      { id: "enugu-north-ward-11-pu-028", code: "028", name: "CUSTOM/HANSA AVENUE II" },
      { id: "enugu-north-ward-11-pu-029", code: "029", name: "CUSTOM/HANSA AVENUE III" },
      { id: "enugu-north-ward-11-pu-030", code: "030", name: "UMUNEVO OGUI NIKE VILLAGE SQUARE I" },
      { id: "enugu-north-ward-11-pu-031", code: "031", name: "UMUNEVO OGUI NIKE VILLAGE SQUARE II" },
      { id: "enugu-north-ward-11-pu-032", code: "032", name: "UMUNEVO OGUI NIKE VILLAGE SQUARE III" },
      { id: "enugu-north-ward-11-pu-033", code: "033", name: "UMUNEVO OGUI NIKE VILLAGE SQUARE IV)" },
      { id: "enugu-north-ward-11-pu-034", code: "034", name: "14/04/11/034(OGUI NIKE VILLAGE SQUARE I" },
      { id: "enugu-north-ward-11-pu-035", code: "035", name: "OGUI NIKE VILLAGE SQUARE II" },
      { id: "enugu-north-ward-11-pu-036", code: "036", name: "OGUI NIKE VILLAGE SQUARE III" },
      { id: "enugu-north-ward-11-pu-037", code: "037", name: "OGUI NIKE/UMUNEVO CIVIC CENTRE I" },
      { id: "enugu-north-ward-11-pu-038", code: "038", name: "OGUI NIKE/UMUNEVO CIVIC CENTRE II" },
      { id: "enugu-north-ward-11-pu-039", code: "039", name: "OGUI NIKE/UMUNEVO CIVIC CENTRE III" },
      { id: "enugu-north-ward-11-pu-040", code: "040", name: "OGUI NIKE/UMUNEVO CIVIC CENTRE IV" },
      { id: "enugu-north-ward-11-pu-041", code: "041", name: "OGUI NIKE/UMUNEVO CIVIC CENTRE V" },
      { id: "enugu-north-ward-11-pu-042", code: "042", name: "OGUI NIKE/UMUNEVO CIVIC CENTRE VI" },
      { id: "enugu-north-ward-11-pu-043", code: "043", name: "OGUI NIKE/UMUNEVO CIVIC CENTRE VII" },
      { id: "enugu-north-ward-11-pu-044", code: "044", name: "OGUI NIKE/UMUNEVO CIVIC CENTRE VIII" },
      { id: "enugu-north-ward-11-pu-045", code: "045", name: "AGUOWO OGUI NIKE DEV. CENTRE I" },
      { id: "enugu-north-ward-11-pu-046", code: "046", name: "AGUOWO OGUI NIKE DEV. CENTRE II" },
    ],
  },

  // ============================================================
  // WARD 12 — UDI SIDING/IVA VALLEY
  // ============================================================

  {
    id: "enugu-north-ward-12",
    code: "12",
    name: "UDI SIDING/IVA VALLEY",
    pollingUnits: [
      { id: "enugu-north-ward-12-pu-001", code: "001", name: "COLLIERY HALL I" },
      { id: "enugu-north-ward-12-pu-002", code: "002", name: "COLLIERY HALL II" },
      { id: "enugu-north-ward-12-pu-003", code: "003", name: "COLLIERY HALL III" },
      { id: "enugu-north-ward-12-pu-004", code: "004", name: "ST. PATRICK’S IVA-VALLEY I" },
      { id: "enugu-north-ward-12-pu-005", code: "005", name: "ST. PATRICK’S IVA-VALLEY II" },
      { id: "enugu-north-ward-12-pu-006", code: "006", name: "COLLIERY PRIMARY SCHOOL" },
      { id: "enugu-north-ward-12-pu-007", code: "007", name: "IVA-VALLEY PRIMARY SCHOOL" },
      { id: "enugu-north-ward-12-pu-008", code: "008", name: "CAMP II IVA-VALLEY I" },
      { id: "enugu-north-ward-12-pu-009", code: "009", name: "CAMP II IVA-VALLEY II" },
      { id: "enugu-north-ward-12-pu-010", code: "010", name: "CAMP II IVA-VALLEY III" },
      { id: "enugu-north-ward-12-pu-011", code: "011", name: "CAMP II IVA-VALLEY IV" },
      { id: "enugu-north-ward-12-pu-012", code: "012", name: "POTTERY IVA-VALLEY I" },
      { id: "enugu-north-ward-12-pu-013", code: "013", name: "POTTERY IVA-VALLEY II" },
      { id: "enugu-north-ward-12-pu-014", code: "014", name: "POTTERY IVA-VALLEY III" },
      { id: "enugu-north-ward-12-pu-015", code: "015", name: "POTTERY IVA-VALLEY IV" },
      { id: "enugu-north-ward-12-pu-016", code: "016", name: "POTTERY IVA-VALLEY V" },
      { id: "enugu-north-ward-12-pu-017", code: "017", name: "WELFARE HALL I" },
      { id: "enugu-north-ward-12-pu-018", code: "018", name: "WELFARE HALL II" },
      { id: "enugu-north-ward-12-pu-019", code: "019", name: "WELFARE HALL III" },
      { id: "enugu-north-ward-12-pu-020", code: "020", name: "PRISON’S CLUB I" },
      { id: "enugu-north-ward-12-pu-021", code: "021", name: "PRISON’S CLUB II" },
      { id: "enugu-north-ward-12-pu-022", code: "022", name: "PRISON’S CLUB III" },
      { id: "enugu-north-ward-12-pu-023", code: "023", name: "PRISON’S CLUB IV" },
      { id: "enugu-north-ward-12-pu-024", code: "024", name: "UGWUAKULU PRIMARY SCHOOL ENUGU NGWO I" },
      { id: "enugu-north-ward-12-pu-025", code: "025", name: "UGWUAKULU PRIMARY SCHOOL ENUGU NGWO II" },
      { id: "enugu-north-ward-12-pu-026", code: "026", name: "COLLIERY TECH. SCHOOL I" },
      { id: "enugu-north-ward-12-pu-027", code: "027", name: "COLLIERY TECH. SCHOOL II" },
      { id: "enugu-north-ward-12-pu-028", code: "028", name: "INDUSTRIAL MISSION NGWO" },
      { id: "enugu-north-ward-12-pu-029", code: "029", name: "ARIA ROAD PRIMARY SCHOOL I" },
      { id: "enugu-north-ward-12-pu-030", code: "030", name: "ARIA ROAD PRIMARY SCHOOL II" },
      { id: "enugu-north-ward-12-pu-031", code: "031", name: "HILL-TOP NGWO I" },
      { id: "enugu-north-ward-12-pu-032", code: "032", name: "HILL-TOP NGWO II" },
      { id: "enugu-north-ward-12-pu-033", code: "033", name: "HILL-TOP NGWO III" },
      { id: "enugu-north-ward-12-pu-034", code: "034", name: "HILL-TOP NGWO IV" },
      { id: "enugu-north-ward-12-pu-035", code: "035", name: "WELFARE HALL" },
      { id: "enugu-north-ward-12-pu-036", code: "036", name: "UGWU AKULU PRIMARY SCHOOL ENUGU NGWO III" },
      { id: "enugu-north-ward-12-pu-037", code: "037", name: "UGWU AKULU PRIMARY SCHOOL ENUGU NGWO IV" },
      { id: "enugu-north-ward-12-pu-038", code: "038", name: "UGWU AKULU PRIMARY SCHOOL ENUGU NGWO V" },
      { id: "enugu-north-ward-12-pu-039", code: "039", name: "HILL TOP NGWO V" },
      { id: "enugu-north-ward-12-pu-040", code: "040", name: "HILL TOP NGWO VI" },
      { id: "enugu-north-ward-12-pu-041", code: "041", name: "CAMP II IVA VALLEY" },
      { id: "enugu-north-ward-12-pu-042", code: "042", name: "ARIA ROAD PRIMARY SCHOOL III" },
      { id: "enugu-north-ward-12-pu-043", code: "043", name: "IVA-VALLEY HEALTH CENTRE, UGWU PEAK" },
      { id: "enugu-north-ward-12-pu-044", code: "044", name: "HILL TOP PRIMARY SCHOOL" },
      { id: "enugu-north-ward-12-pu-045", code: "045", name: "COMMUNITY SECONDARY SCHOOL, IVA-VALLEY" },
      { id: "enugu-north-ward-12-pu-046", code: "046", name: "ODAGHIJI VANGARD, IVA-VALLEY" },
      { id: "enugu-north-ward-12-pu-047", code: "047", name: "ABUJA ISIYI-ARIA ROAD" },
      { id: "enugu-north-ward-12-pu-048", code: "048", name: "NGWO CAMP II HALL BUNKER I" },
      { id: "enugu-north-ward-12-pu-049", code: "049", name: "NGWO CAMP II HALL BUNKER II" },
      { id: "enugu-north-ward-12-pu-050", code: "050", name: "NGWO CAMP II HALL BUNKER III" },
      { id: "enugu-north-ward-12-pu-051", code: "051", name: "NGWO CAMP I FIELD I" },
      { id: "enugu-north-ward-12-pu-052", code: "052", name: "NGWO CAMP I FIELD II" },
      { id: "enugu-north-ward-12-pu-053", code: "053", name: "OLD UNTH" },
      { id: "enugu-north-ward-12-pu-054", code: "054", name: "UDI-SIDING FOOTBALL FIELD I" },
      { id: "enugu-north-ward-12-pu-055", code: "055", name: "UDI-SIDING FOOTBALL FIELD II" },
      { id: "enugu-north-ward-12-pu-056", code: "056", name: "UDI-SIDING FOOTBALL FIELD III" },
    ],
  },

  // ============================================================
  // WARD 13 — OGUI TOWNSHIP
  // ============================================================

  {
    id: "enugu-north-ward-13",
    code: "13",
    name: "OGUI TOWNSHIP",
    pollingUnits: [
      { id: "enugu-north-ward-13-pu-001", code: "001", name: "SALVATION ARMY PRIMARY SCHOOL I" },
      { id: "enugu-north-ward-13-pu-002", code: "002", name: "SALVATION ARMY PRIMARY SCHOOL II" },
      { id: "enugu-north-ward-13-pu-003", code: "003", name: "SALVATION ARMY PRIMARY SCHOOL III" },
      { id: "enugu-north-ward-13-pu-004", code: "004", name: "SALVATION ARMY PRIMARY SCHOOL IV" },
      { id: "enugu-north-ward-13-pu-005", code: "005", name: "METHODIST PRIMARY SCHOOL I" },
      { id: "enugu-north-ward-13-pu-006", code: "006", name: "METHODIST PRIMARY SCHOOL II" },
      { id: "enugu-north-ward-13-pu-007", code: "007", name: "METHODIST PRIMARY SCHOOL III" },
      { id: "enugu-north-ward-13-pu-008", code: "008", name: "CARTER STREET PRIMARY SCHOOL I" },
      { id: "enugu-north-ward-13-pu-009", code: "009", name: "CARTER STREET PRIMARY SCHOOL II" },
      { id: "enugu-north-ward-13-pu-010", code: "010", name: "CARTER STREET PRIMARY SCHOOL III" },
      { id: "enugu-north-ward-13-pu-011", code: "011", name: "CARTER STREET PRIMARY SCHOOL IV" },
      { id: "enugu-north-ward-13-pu-012", code: "012", name: "CARTER STREET PRIMARY SCHOOL V" },
      { id: "enugu-north-ward-13-pu-013", code: "013", name: "METHODIST PRIMARY SCHOOL IV" },
      { id: "enugu-north-ward-13-pu-014", code: "014", name: "METHODIST PRIMARY SCHOOL V" },
      { id: "enugu-north-ward-13-pu-015", code: "015", name: "MOORE HOUSE STREET PRIMARY SCHOOL" },
      { id: "enugu-north-ward-13-pu-016", code: "016", name: "RECREATION CLUB-OPP. STADIUM" },
      { id: "enugu-north-ward-13-pu-017", code: "017", name: "CARTER STREET HEALTH CENTRE I" },
      { id: "enugu-north-ward-13-pu-018", code: "018", name: "CARTER STREET HEALTH CENTRE II" },
    ],
  },
];