export const enuguEastElectoralData: Ward[] = [
  // ============================================================
  // WARD 01 - ABAKPA I
  // ============================================================
  {
    id: "enugu-east-ward-01",
    code: "01",
    name: "ABAKPA I",
    pollingUnits: [
      { id: "enugu-east-ward-01-pu-001", code: "001", name: "ABAKPA VILLAGE PRIMARY SCHOOL I" },
      { id: "enugu-east-ward-01-pu-002", code: "002", name: "ABAKPA VILLAGE PRIMARY SCHOOL II" },
      { id: "enugu-east-ward-01-pu-003", code: "003", name: "ABAKPA VILLAGE PRIMARY SCHOOL III" },
      { id: "enugu-east-ward-01-pu-004", code: "004", name: "ABAKPA VILLAGE PRIMARY SCHOOL IV" },
      { id: "enugu-east-ward-01-pu-005", code: "005", name: "ABAKPA VILLAGE PRIMARY SCHOOL V" },
      { id: "enugu-east-ward-01-pu-006", code: "006", name: "ABAKPA VILLAGE PRIMARY SCHOOL VI" },
      { id: "enugu-east-ward-01-pu-007", code: "007", name: "ABAKPA VILLAGE PRIMARY SCHOOL VII" },
      { id: "enugu-east-ward-01-pu-008", code: "008", name: "ABAKPA VILLAGE PRIMARY SCHOOL VIII" },
      { id: "enugu-east-ward-01-pu-009", code: "009", name: "ABAKPA VILLAGE PRIMARY SCHOOL IX" },
      { id: "enugu-east-ward-01-pu-010", code: "010", name: "ABAKPA VILLAGE PRIMARY SCHOOL X" },
      { id: "enugu-east-ward-01-pu-011", code: "011", name: "ABAKPA VILLAGE PRIMARY SCHOOL XI" },
      { id: "enugu-east-ward-01-pu-012", code: "012", name: "HOUSING ESTATE PRIMARY SCHOOL I" },
      { id: "enugu-east-ward-01-pu-013", code: "013", name: "HOUSING ESTATE PRIMARY SCHOOL II" },
      { id: "enugu-east-ward-01-pu-014", code: "014", name: "HOUSING ESTATE PRIMARY SCHOOL III" },
      { id: "enugu-east-ward-01-pu-015", code: "015", name: "HOUSING ESTATE PRIMARY SCHOOL IV" },
      { id: "enugu-east-ward-01-pu-016", code: "016", name: "HOUSING ESTATE PRIMARY SCHOOL V" },
      { id: "enugu-east-ward-01-pu-017", code: "017", name: "HOUSING ESTATE PRIMARY SCHOOL VI" },
      { id: "enugu-east-ward-01-pu-018", code: "018", name: "HOUSING ESTATE PRIMARY SCHOOL VII" },
      { id: "enugu-east-ward-01-pu-019", code: "019", name: "HOUSING ESTATE PRIMARY SCHOOL VIII" },
      { id: "enugu-east-ward-01-pu-020", code: "020", name: "HOUSING ESTATE PRIMARY SCHOOL IX" },
      { id: "enugu-east-ward-01-pu-021", code: "021", name: "HOUSING ESTATE PRIMARY SCHOOL X" },
      { id: "enugu-east-ward-01-pu-022", code: "022", name: "NATIONAL GRAMMAR SCHOOL I" },
      { id: "enugu-east-ward-01-pu-023", code: "023", name: "NATIONAL GRAMMAR SCHOOL II" },
      { id: "enugu-east-ward-01-pu-024", code: "024", name: "NATIONAL GRAMMAR SCHOOL III" },
      { id: "enugu-east-ward-01-pu-025", code: "025", name: "NATIONAL GRAMMAR SCHOOL IV" },
      { id: "enugu-east-ward-01-pu-026", code: "026", name: "NATIONAL GRAMMAR SCHOOL V" },
      { id: "enugu-east-ward-01-pu-027", code: "027", name: "NATIONAL GRAMMAR SCHOOL VI" },
      { id: "enugu-east-ward-01-pu-028", code: "028", name: "ABAKALIKI ROAD PRIMARY SCHOOL I" },
      { id: "enugu-east-ward-01-pu-029", code: "029", name: "ABAKALIKI ROAD PRIMARY SCHOOL II" },
      { id: "enugu-east-ward-01-pu-030", code: "030", name: "ABAKALIKI ROAD PRIMARY SCHOOL III" },
      { id: "enugu-east-ward-01-pu-031", code: "031", name: "ABAKALIKI ROAD PRIMARY SCHOOL IV" },
      { id: "enugu-east-ward-01-pu-032", code: "032", name: "ABAKPA GIRLS SEC. SCH. I" },
      { id: "enugu-east-ward-01-pu-033", code: "033", name: "ABAKPA GIRLS SEC. SCH. II" },
      { id: "enugu-east-ward-01-pu-034", code: "034", name: "HEALTH CENTRE AMAETITI ABAKPA" },
      { id: "enugu-east-ward-01-pu-035", code: "035", name: "AKARA JUNCTION UGBOGHE" },
      { id: "enugu-east-ward-01-pu-036", code: "036", name: "UGBOWA MARKET SQUARE" },
      { id: "enugu-east-ward-01-pu-037", code: "037", name: "OPPOSITE SLAUGHTER HOUSE" },
      { id: "enugu-east-ward-01-pu-038", code: "038", name: "GATE OF ABAKPA LICENCE OFFICE" },
      { id: "enugu-east-ward-01-pu-039", code: "039", name: "ABAKPA 1ST BUS STOP" },
      { id: "enugu-east-ward-01-pu-040", code: "040", name: "NDOMIRI JUNCTION ABAKPA" },
      { id: "enugu-east-ward-01-pu-041", code: "041", name: "NDOMMIRI SQUARE" },
      { id: "enugu-east-ward-01-pu-042", code: "042", name: "TAZOL BUS STOP UGBOGHE" },
      { id: "enugu-east-ward-01-pu-043", code: "043", name: "UGBOGHE CENTRAL" },
      { id: "enugu-east-ward-01-pu-044", code: "044", name: "AMAUZARI UNITY HALL" },
      { id: "enugu-east-ward-01-pu-045", code: "045", name: "ABAKPA CENTRAL I ACHI STREET" },
      { id: "enugu-east-ward-01-pu-046", code: "046", name: "SUNDAY SUNDAY FIELD I" },
      { id: "enugu-east-ward-01-pu-047", code: "047", name: "SUNDAY SUNDAY FIELD II" },
      { id: "enugu-east-ward-01-pu-048", code: "048", name: "SUNDAY SUNDAY FIELD III" },
      { id: "enugu-east-ward-01-pu-049", code: "049", name: "HOUSING ESTATE SHOPPING COMPLEX I" },
      { id: "enugu-east-ward-01-pu-050", code: "050", name: "HOUSING ESTATE SHOPPING COMPLEX II" },
      { id: "enugu-east-ward-01-pu-051", code: "051", name: "HOUSING ESTATE SHOPPING COMPLEX III" },
      { id: "enugu-east-ward-01-pu-052", code: "052", name: "HOUSING STATE WATER TANK" },
      { id: "enugu-east-ward-01-pu-053", code: "053", name: "THINKER’S CORNER ESTATE BEHIND GRAMMAR SCHOOL" },
      { id: "enugu-east-ward-01-pu-054", code: "054", name: "UGBOCHIME I ABAKPA" },
      { id: "enugu-east-ward-01-pu-055", code: "055", name: "UGBOCHIME II ABAKPA" },
      { id: "enugu-east-ward-01-pu-056", code: "056", name: "GODFREY OKOYE UNIVERSITY JUNCTION" },
      { id: "enugu-east-ward-01-pu-057", code: "057", name: "GODFREY OKOYE UNIVERSITY 1ST GATE I" },
      { id: "enugu-east-ward-01-pu-058", code: "058", name: "GODFREY OKOYE UNIVERSITY 1ST GATE II" },
      { id: "enugu-east-ward-01-pu-059", code: "059", name: "AIRPORT ROAD EXTENSION" },
      { id: "enugu-east-ward-01-pu-060", code: "060", name: "POLICE CHIDREN SCH I" },
      { id: "enugu-east-ward-01-pu-061", code: "061", name: "POLICE CHIDREN’S SCH II ABAKPA EXPRESSWAY" },
     { id: "enugu-east-ward-01-pu-062", code: "062", name: "NATIONAL ORTHOPEDIC HOSPITAL GATE 2" },   { id: "enugu-east-ward-01-pu-063", code: "063", name: "NATIONAL ORTHOPEDIC HOSPITAL GATE 3" },
      { id: "enugu-east-ward-01-pu-064", code: "064", name: "UGBO PAUL JUNCTION I" },
      { id: "enugu-east-ward-01-pu-065", code: "065", name: "UGBOEZEJI COMM. HALL" },
      { id: "enugu-east-ward-01-pu-066", code: "066", name: "UGBOEZEJI COMM. SQUARE" },
      { id: "enugu-east-ward-01-pu-067", code: "067", name: "IFO FIELD I" },
      { id: "enugu-east-ward-01-pu-068", code: "068", name: "IFO FIELD II" },
      { id: "enugu-east-ward-01-pu-069", code: "069", name: "UZOAVA RIVER NIKE UGBOEZEJI" },
      { id: "enugu-east-ward-01-pu-070", code: "070", name: "UGBO PAUL JUNCTION ABAKPA II" },
      { id: "enugu-east-ward-01-pu-071", code: "071", name: "UPPER HOUSING FARMER LAYOUT" },
    ],
  },

  // ============================================================
  // WARD 02 - ABAKPA II
  // ============================================================
  {
    id: "enugu-east-ward-02",
    code: "02",
    name: "ABAKPA II",
    pollingUnits: [
      { id: "enugu-east-ward-02-pu-001", code: "001", name: "UGWOGO/NNAJI PARK I" },
      { id: "enugu-east-ward-02-pu-002", code: "002", name: "UGWOGO/NNAJI PARK II" },
      { id: "enugu-east-ward-02-pu-003", code: "003", name: "UGWOGO/NNAJI PARK III" },
      { id: "enugu-east-ward-02-pu-004", code: "004", name: "UGWOGO/NNAJI PARK IV" },
      { id: "enugu-east-ward-02-pu-005", code: "005", name: "UGWOGO/NNAJI PARK V" },
      { id: "enugu-east-ward-02-pu-006", code: "006", name: "UGWOGO/NNAJI PARK VI" },
      { id: "enugu-east-ward-02-pu-007", code: "007", name: "UGWOGO/NNAJI PARK VII" },
      { id: "enugu-east-ward-02-pu-008", code: "008", name: "UGWOGO/NNAJI PARK VIII" },
      { id: "enugu-east-ward-02-pu-009", code: "009", name: "UGWOGO/NNAJI PARK IX" },
      { id: "enugu-east-ward-02-pu-010", code: "010", name: "TIPPER PARK I" },
      { id: "enugu-east-ward-02-pu-011", code: "011", name: "TIPPER PARK II" },
      { id: "enugu-east-ward-02-pu-012", code: "012", name: "TIPPER PARK III" },
      { id: "enugu-east-ward-02-pu-013", code: "013", name: "TIPPER PARK IV" },
      { id: "enugu-east-ward-02-pu-014", code: "014", name: "TIPPER PARK V" },
      { id: "enugu-east-ward-02-pu-015", code: "015", name: "TIPPER PARK VI" },
      { id: "enugu-east-ward-02-pu-016", code: "016", name: "TIPPER PARK VII" },
      { id: "enugu-east-ward-02-pu-017", code: "017", name: "TIPPER PARK VIII" },
      { id: "enugu-east-ward-02-pu-018", code: "018", name: "TIPPER PARK IX" },
      { id: "enugu-east-ward-02-pu-019", code: "019", name: "TIPPER PARK X" },
      { id: "enugu-east-ward-02-pu-020", code: "020", name: "FEDERAL HOUSING PRIMARY SCHOOL I" },
      { id: "enugu-east-ward-02-pu-021", code: "021", name: "FEDERAL HOUSING PRIMARY SCHOOL II" },
      { id: "enugu-east-ward-02-pu-022", code: "022", name: "BENICO BUS STOP UGBENE I" },
      { id: "enugu-east-ward-02-pu-023", code: "023", name: "IWENE TANSI SQUARE" },
      { id: "enugu-east-ward-02-pu-024", code: "024", name: "UGWUNWANI SQUARE" },
      { id: "enugu-east-ward-02-pu-025", code: "025", name: "BENARD ANIKE JUNCTION" },
      { id: "enugu-east-ward-02-pu-026", code: "026", name: "UKWUNWAMENE SQUARE" },
      { id: "enugu-east-ward-02-pu-027", code: "027", name: "ANAZODO BUS STOP UGHENE I" },
      { id: "enugu-east-ward-02-pu-028", code: "028", name: "TOBAIS BUS STOP UGBENE I" },
      { id: "enugu-east-ward-02-pu-029", code: "029", name: "UGWUNWANI BUS STOP IKEGBUNAM" },
      { id: "enugu-east-ward-02-pu-030", code: "030", name: "OTAKAGU SQUARE" },
      { id: "enugu-east-ward-02-pu-031", code: "031", name: "OSMOND BUS STOP UGBENE I" },
      { id: "enugu-east-ward-02-pu-032", code: "032", name: "UGWU AKUBUEZE SQUARE" },
      { id: "enugu-east-ward-02-pu-033", code: "033", name: "OBIEZE SQUARE I" },
      { id: "enugu-east-ward-02-pu-034", code: "034", name: "OBIEZE SQUARE II" },
      { id: "enugu-east-ward-02-pu-035", code: "035", name: "ELIAS BANABAS JUNCTION I" },
      { id: "enugu-east-ward-02-pu-036", code: "036", name: "ELIAS BANABAS JUNCTION II" },
      { id: "enugu-east-ward-02-pu-037", code: "037", name: "AVA STREAM OGWUAGU" },
      { id: "enugu-east-ward-02-pu-038", code: "038", name: "IDEMIRI OGWUAGO SQUARE" },
      { id: "enugu-east-ward-02-pu-039", code: "039", name: "OZOANI JUNCTION" },
      { id: "enugu-east-ward-02-pu-040", code: "040", name: "FRANK EZE MIRABETH JUNCTION" },
      { id: "enugu-east-ward-02-pu-041", code: "041", name: "EZEBUDE SQUARE OGWUGO" },
      { id: "enugu-east-ward-02-pu-042", code: "042", name: "NEVO / OZOANI JUNCTION" },
      { id: "enugu-east-ward-02-pu-043", code: "043", name: "VASCO / EZEAMA JUNCTION OGWUAGO" },
      { id: "enugu-east-ward-02-pu-044", code: "044", name: "FESTAC AVENUE FEDERAL HOUSING" },
      { id: "enugu-east-ward-02-pu-045", code: "045", name: "ZARIA AVENUE FEDERAL HOUSING" },
    ],
  },

  // ============================================================
  // WARD 03 - UMUENWENE
  // ============================================================
  {
    id: "enugu-east-ward-03",
    code: "03",
    name: "UMUENWENE",
    pollingUnits: [
      { id: "enugu-east-ward-03-pu-001", code: "001", name: "NIKE TOWN HALL I" },
      { id: "enugu-east-ward-03-pu-002", code: "002", name: "NIKE TOWN HALL II" },
      { id: "enugu-east-ward-03-pu-003", code: "003", name: "NIKE TOWN HALL III" },
      { id: "enugu-east-ward-03-pu-004", code: "004", name: "NIKE TOWN HALL IV" },
      { id: "enugu-east-ward-03-pu-005", code: "005", name: "NIKE TOWN HALL V" },
      { id: "enugu-east-ward-03-pu-006", code: "006", name: "OBINAGU VILLA I" },
      { id: "enugu-east-ward-03-pu-007", code: "007", name: "OBINAGU VILLA II" },
      { id: "enugu-east-ward-03-pu-008", code: "008", name: "OBINAGU VILLAGE SQUARE I" },
      { id: "enugu-east-ward-03-pu-009", code: "009", name: "OBINAGU VILLAGE SQUARE II" },
      { id: "enugu-east-ward-03-pu-010", code: "010", name: "UGBO EMMA I" },
      { id: "enugu-east-ward-03-pu-011", code: "011", name: "UGBO EMMA II" },
      { id: "enugu-east-ward-03-pu-012", code: "012", name: "UGWUEKE VILLAGE SQUARE I" },
      { id: "enugu-east-ward-03-pu-013", code: "013", name: "UGWUEKE VILLAGE SQUARE II" },
      { id: "enugu-east-ward-03-pu-014", code: "014", name: "BACK TO LAND SQUARE AMANGWU I" },
      { id: "enugu-east-ward-03-pu-015", code: "015", name: "BACK TO LAND SQUARE AMANGWU II" },
      { id: "enugu-east-ward-03-pu-016", code: "016", name: "AMANGWU VILLAGE SQUARE I" },
      { id: "enugu-east-ward-03-pu-017", code: "017", name: "AMANGWU VILLAGE SQUARE II" },
      { id: "enugu-east-ward-03-pu-018", code: "018", name: "ODANGENE VILLAGE SQUARE I" },
      { id: "enugu-east-ward-03-pu-019", code: "019", name: "ODANGENE VILLAGE SQUARE II" },
      { id: "enugu-east-ward-03-pu-020", code: "020", name: "UMUENWENE 48TH AVENUE I" },
      { id: "enugu-east-ward-03-pu-021", code: "021", name: "UMUENWENE 48TH AVENUE II" },
      { id: "enugu-east-ward-03-pu-022", code: "022", name: "UMUENWENE 48TH AVENUE III" },
      { id: "enugu-east-ward-03-pu-023", code: "023", name: "UMUENWENE IJI NIKE LAST BUS STOP I" },
      { id: "enugu-east-ward-03-pu-024", code: "024", name: "UMUENWENE IJI NIKE LAST BUS STOP II" },
      { id: "enugu-east-ward-03-pu-025", code: "025", name: "ARIAKU LAYOUT UMUENWENE" },
      { id: "enugu-east-ward-03-pu-026", code: "026", name: "IFENZE JUNCTION UMUENWENE" },
      { id: "enugu-east-ward-03-pu-027", code: "027", name: "DEVELOPMENT CENTRE AMANGWO IJI NIKE I" },
      { id: "enugu-east-ward-03-pu-028", code: "028", name: "DEVELOPMENT CENTRE AMANGWO IJI NIKE II" },
      { id: "enugu-east-ward-03-pu-029", code: "029", name: "OBINAGU VILLAGE EXTENSION I" },
      { id: "enugu-east-ward-03-pu-030", code: "030", name: "OBINAGU VILLAGE EXTENSION II" },
      { id: "enugu-east-ward-03-pu-031", code: "031", name: "OBINAGU VILLAGE KEKE BUS STOP" },
      { id: "enugu-east-ward-03-pu-032", code: "032", name: "OBINAGU ROAD JUNCTION I" },
      { id: "enugu-east-ward-03-pu-033", code: "033", name: "OBINAGU ROAD JUNCTION II" },
      { id: "enugu-east-ward-03-pu-034", code: "034", name: "IKPEAMA JUNCTION" },
      { id: "enugu-east-ward-03-pu-035", code: "035", name: "CORNERSTONE I" },
      { id: "enugu-east-ward-03-pu-036", code: "036", name: "CORNERSTONE II" },
      { id: "enugu-east-ward-03-pu-037", code: "037", name: "ONUNGENE SQUARE I" },
      { id: "enugu-east-ward-03-pu-038", code: "038", name: "ONUNGENE SQUARE II" },
      { id: "enugu-east-ward-03-pu-039", code: "039", name: "CORNERSTONE AVENUE" },
    ],
  },

  // ============================================================
  // WARD 04 - AMORJI
  // ============================================================
  {
    id: "enugu-east-ward-04",
    code: "04",
    name: "AMORJI",
    pollingUnits: [
      { id: "enugu-east-ward-04-pu-001", code: "001", name: "C.P.S. AMORJI I" },
      { id: "enugu-east-ward-04-pu-002", code: "002", name: "C.P.S. AMORJI II" },
      { id: "enugu-east-ward-04-pu-003", code: "003", name: "C.P.S AMORJI III" },
      { id: "enugu-east-ward-04-pu-004", code: "004", name: "C.P.S. AMORJI IV" },
      { id: "enugu-east-ward-04-pu-005", code: "005", name: "CIVIC CENTRE AMORJI III" },
      { id: "enugu-east-ward-04-pu-006", code: "006", name: "CIVIC CENTRE I" },
      { id: "enugu-east-ward-04-pu-007", code: "007", name: "CIVIC CENTRE II" },
      { id: "enugu-east-ward-04-pu-008", code: "008", name: "AKAMA VILLAGE SQUARE" },
      { id: "enugu-east-ward-04-pu-009", code: "009", name: "UGBO AKAMA" },
      { id: "enugu-east-ward-04-pu-010", code: "010", name: "OPEN SPACE ALONG AMORJI ROAD" },
      { id: "enugu-east-ward-04-pu-011", code: "011", name: "UMUNWOKA HALL AMORJI NIKE" },
      { id: "enugu-east-ward-04-pu-012", code: "012", name: "ISHIENU SQAURE AMORJI NIKE" },
      { id: "enugu-east-ward-04-pu-013", code: "013", name: "OPEN SPACE UPPER AMORJI" },
      { id: "enugu-east-ward-04-pu-014", code: "014", name: "UGBO AMORJI" },
      { id: "enugu-east-ward-04-pu-015", code: "015", name: "OPEN SPACE NEAR HEALTH CENTRE AMORJI NIKE" },
      { id: "enugu-east-ward-04-pu-016", code: "016", name: "OPEN SPACE OPPOSITE MARIDO CITY LAYOUT AMORJI NIKE" },
    ],
  },

  // ============================================================
  // WARD 05 - MBULUIYIUKWU
  // ============================================================
  {
    id: "enugu-east-ward-05",
    code: "05",
    name: "MBULUIYIUKWU",
    pollingUnits: [
      { id: "enugu-east-ward-05-pu-001", code: "001", name: "C.P.S. AKO NIKE I" },
      { id: "enugu-east-ward-05-pu-002", code: "002", name: "C.P.S. AKO NIKE II" },
      { id: "enugu-east-ward-05-pu-003", code: "003", name: "C.P.S. AKO NIKE III" },
      { id: "enugu-east-ward-05-pu-004", code: "004", name: "C.P.S. AKO NIKE IV" },
      { id: "enugu-east-ward-05-pu-005", code: "005", name: "C.P.S. AGBOGAZI NIKE I" },
      { id: "enugu-east-ward-05-pu-006", code: "006", name: "C.P.S. AGBOGAZI NIKE II" },
      { id: "enugu-east-ward-05-pu-007", code: "007", name: "C.P.S. OGBEKE NIKE I" },
      { id: "enugu-east-ward-05-pu-008", code: "008", name: "C.P.S. OGBEKE NIKE II" },
      { id: "enugu-east-ward-05-pu-009", code: "009", name: "C.P.S. NEKE UNO I" },
      { id: "enugu-east-ward-05-pu-010", code: "010", name: "C.P.S. NEKE UNO II" },
      { id: "enugu-east-ward-05-pu-011", code: "011", name: "C.P.S. NEKE ODENIGBO I" },
      { id: "enugu-east-ward-05-pu-012", code: "012", name: "C.P.S. NEKE ODENIGBO II" },
      { id: "enugu-east-ward-05-pu-013", code: "013", name: "C.P.S. AGBOGAZI NIKE III" },
      { id: "enugu-east-ward-05-pu-014", code: "014", name: "C.P.S. AGBOGAZI NIKE IV" },
    ],
  },

  // ============================================================
  // WARD 06 - MBULUOWEHE
  // ============================================================
  {
    id: "enugu-east-ward-06",
    code: "06",
    name: "MBULUOWEHE",
    pollingUnits: [
      { id: "enugu-east-ward-06-pu-001", code: "001", name: "C.P.S. AMOKPO I" },
      { id: "enugu-east-ward-06-pu-002", code: "002", name: "C.P.S. AMOKPO II" },
      { id: "enugu-east-ward-06-pu-003", code: "003", name: "C.P.S. AMOKPO III" },
      { id: "enugu-east-ward-06-pu-004", code: "004", name: "ALULU VILLAGE SQUARE I" },
      { id: "enugu-east-ward-06-pu-005", code: "005", name: "ALULU VILLAGE SQUARE II" },
      { id: "enugu-east-ward-06-pu-006", code: "006", name: "ALULU VILLAGE SQUARE III" },
      { id: "enugu-east-ward-06-pu-007", code: "007", name: "UGBO NOKPA" },
      { id: "enugu-east-ward-06-pu-008", code: "008", name: "AGU AMOKPO" },
      { id: "enugu-east-ward-06-pu-009", code: "009", name: "C.P.S. AMOKPO IV" },
      { id: "enugu-east-ward-06-pu-010", code: "010", name: "NOKPA VILLAGE SQUARE" },
      { id: "enugu-east-ward-06-pu-011", code: "011", name: "AMOKPO VILLAGE SQUARE" },
      { id: "enugu-east-ward-06-pu-012", code: "012", name: "EZEMA VILLAGE SQUARE" },
      { id: "enugu-east-ward-06-pu-013", code: "013", name: "UMUOGBE VILLAGE SQUARE" },
      { id: "enugu-east-ward-06-pu-014", code: "014", name: "ALULU VILLAGE SQUARE HALL" },
      { id: "enugu-east-ward-06-pu-015", code: "015", name: "UJE VILLAGE CENTRE AMOKPO" },
      { id: "enugu-east-ward-06-pu-016", code: "016", name: "UPPER EZIAMA SQAURE" },
    ],
  },


    // ============================================================
  // WARD 07 - MBULU-NJODO WEST
  // ============================================================
  {
    id: "enugu-east-ward-07",
    code: "07",
    name: "MBULU-NJODO WEST",
    pollingUnits: [
      { id: "enugu-east-ward-07-pu-001", code: "001", name: "TOWN SCHOOL EMENE I" },
      { id: "enugu-east-ward-07-pu-002", code: "002", name: "TOWN SCHOOL EMENE II" },
      { id: "enugu-east-ward-07-pu-003", code: "003", name: "TOWN SCHOOL EMENE III" },
      { id: "enugu-east-ward-07-pu-004", code: "004", name: "TOWN SCHOOL EMENE IV" },
      { id: "enugu-east-ward-07-pu-005", code: "005", name: "CENTRAL SCHOOL EMENE I" },
      { id: "enugu-east-ward-07-pu-006", code: "006", name: "CENTRAL SCHOOL EMENE II" },
      { id: "enugu-east-ward-07-pu-007", code: "007", name: "CENTRAL SCHOOL EMENE III" },
      { id: "enugu-east-ward-07-pu-008", code: "008", name: "CENTRAL SCHOOL EMENE IV" },
      { id: "enugu-east-ward-07-pu-009", code: "009", name: "CENTRAL SCHOOL EMENE V" },
      { id: "enugu-east-ward-07-pu-010", code: "010", name: "CENTRAL SCHOOL EMENE VI" },
      { id: "enugu-east-ward-07-pu-011", code: "011", name: "PRACTISING SCHOOL EMENE I" },
      { id: "enugu-east-ward-07-pu-012", code: "012", name: "PRACTISING SCHOOL EMENE II" },
      { id: "enugu-east-ward-07-pu-013", code: "013", name: "PRACTISING SCHOOL EMENE III" },
      { id: "enugu-east-ward-07-pu-014", code: "014", name: "PRACTISING SCHOOL EMENE IV" },
      { id: "enugu-east-ward-07-pu-015", code: "015", name: "PRACTISING SCHOOL EMENE V" },
      { id: "enugu-east-ward-07-pu-016", code: "016", name: "OBINAGU TOWN I" },
      { id: "enugu-east-ward-07-pu-017", code: "017", name: "OBINAGU TOWN II" },
      { id: "enugu-east-ward-07-pu-018", code: "018", name: "NCHATANCHA SQUARE I" },
      { id: "enugu-east-ward-07-pu-019", code: "019", name: "NCHATANCHA SQUARE II" },
      { id: "enugu-east-ward-07-pu-020", code: "020", name: "AIRPORT PRIMARY SCHOOL I" },
      { id: "enugu-east-ward-07-pu-021", code: "021", name: "CENTRE FOR DISABLED" },
      { id: "enugu-east-ward-07-pu-022", code: "022", name: "NKPOLOGWU PRIMARY SCHOOL I" },
      { id: "enugu-east-ward-07-pu-023", code: "023", name: "NKPOLOGWU PRIMARY SCHOOL II" },
      { id: "enugu-east-ward-07-pu-024", code: "024", name: "NKPOLOGWU PRIMARY SCHOOL III" },
      { id: "enugu-east-ward-07-pu-025", code: "025", name: "AIRPORT PRIMARY SCHOOL II" },
      { id: "enugu-east-ward-07-pu-026", code: "026", name: "NOME SQUARE AMECHI EMENE" },
      { id: "enugu-east-ward-07-pu-027", code: "027", name: "OTUKWU VILLAGE ASSEMBLY HALL EMENE – NIKE" },
      { id: "enugu-east-ward-07-pu-028", code: "028", name: "NEW ORIE EMENE MARKET" },
      { id: "enugu-east-ward-07-pu-029", code: "029", name: "NKWUGBOR ROAD BY POLICE QUARTERS JUNCTION" },
      { id: "enugu-east-ward-07-pu-030", code: "030", name: "CONRAWS ESTATE JUNCTION NIKE" },
      { id: "enugu-east-ward-07-pu-031", code: "031", name: "VOCATIONAL REHABILITATION CENTRE EMENE" },
      { id: "enugu-east-ward-07-pu-032", code: "032", name: "REHAB ROAD BY IKEIYIAMA STREET EMENE" },
      { id: "enugu-east-ward-07-pu-033", code: "033", name: "NNAMCHI STREET BY MICKOVAT JUNCTION" },
      { id: "enugu-east-ward-07-pu-034", code: "034", name: "OLD ORIE EMENE BY UGA STREET ORIE EMENE" },
      { id: "enugu-east-ward-07-pu-035", code: "035", name: "COMMUNITY HIGH SCH EMENE I" },
      { id: "enugu-east-ward-07-pu-036", code: "036", name: "COMMUNITY HIGH SCH EMENE II" },
      { id: "enugu-east-ward-07-pu-037", code: "037", name: "JOHN OKWOR STREET SQUARE NEAR OWA BUS STOP EMENE" },
      { id: "enugu-east-ward-07-pu-038", code: "038", name: "ANNUACIATION HOSPITAL, EMENE (BACK)" },
      { id: "enugu-east-ward-07-pu-039", code: "039", name: "ANNUACIATION HOSPITAL, EMENE (FRONT)" },
      { id: "enugu-east-ward-07-pu-040", code: "040", name: "NEW SOCIETYBUS STOP" },
      { id: "enugu-east-ward-07-pu-041", code: "041", name: "UKWU MANGO BUS STOP ORIE EMENE" },
      { id: "enugu-east-ward-07-pu-042", code: "042", name: "EKE OBINAGU MARKET" },
      { id: "enugu-east-ward-07-pu-043", code: "043", name: "COMMUNITY PRIMARY SCHOOL OBINAGU NIKE I" },
      { id: "enugu-east-ward-07-pu-044", code: "044", name: "COMMUNITY PRAIMARY SCHOOL OBINAGU NIKE II" },
      { id: "enugu-east-ward-07-pu-045", code: "045", name: "OBINAGU AGBARA VILLAGE SQUARE" },
      { id: "enugu-east-ward-07-pu-046", code: "046", name: "ONOKOLO TIRE SQUARE NCHATANCHA" },
      { id: "enugu-east-ward-07-pu-047", code: "047", name: "OKOLO UBIA OPEN SQUARE" },
      { id: "enugu-east-ward-07-pu-048", code: "048", name: "AFO NCHATANCHA MARKET SQAURE" },
      { id: "enugu-east-ward-07-pu-049", code: "049", name: "AIRPORT STAFF SECONDARY SCHOOL MAINLAND EMENE I" },
      { id: "enugu-east-ward-07-pu-050", code: "050", name: "AIRPORT STAFF SECONDARY SCHOOL MAINLAND II" },
      { id: "enugu-east-ward-07-pu-051", code: "051", name: "JUSTICE JUNCTION BUS STOP BY ADORATION ROAD" },
      { id: "enugu-east-ward-07-pu-052", code: "052", name: "NKPOLOGWU POLICE POST EMENE" },
      { id: "enugu-east-ward-07-pu-053", code: "053", name: "NKPOLOGWU FARM SETTLEMENT ABUJA LINE (SQUARE)" },
      { id: "enugu-east-ward-07-pu-054", code: "054", name: "EMENE POLICE STATION JUNCTION; INDUSTRIAL LAYOUT" },
    ],
  },

  // ============================================================
  // WARD 08 - UMUCHIGBO
  // ============================================================
  {
    id: "enugu-east-ward-08",
    code: "08",
    name: "UMUCHIGBO",
    pollingUnits: [
      { id: "enugu-east-ward-08-pu-001", code: "001", name: "UMUCHIGBO HALL I" },
      { id: "enugu-east-ward-08-pu-002", code: "002", name: "UMUCHIGBO HALL II" },
      { id: "enugu-east-ward-08-pu-003", code: "003", name: "UMUCHIGBO HALL III" },
      { id: "enugu-east-ward-08-pu-004", code: "004", name: "UMUCHIGBO HALL" },
      { id: "enugu-east-ward-08-pu-005", code: "005", name: "FORGEROLL JUNCTION/UDOKA LAYOUT AIRPORT VILLAGE" },
      { id: "enugu-east-ward-08-pu-006", code: "006", name: "UMUCHIGBO HALL" },
      { id: "enugu-east-ward-08-pu-007", code: "007", name: "UGBO OGBURUGBU I" },
      { id: "enugu-east-ward-08-pu-008", code: "008", name: "UGBO OGBURUGBU II" },
      { id: "enugu-east-ward-08-pu-009", code: "009", name: "UMUCHIGBO HALL VI" },
      { id: "enugu-east-ward-08-pu-010", code: "010", name: "UMUCHIGBO HALL VII" },
      { id: "enugu-east-ward-08-pu-011", code: "011", name: "UMUCHIGBO HALL VIII" },
      { id: "enugu-east-ward-08-pu-012", code: "012", name: "UGWUNWODE SQUARE" },
      { id: "enugu-east-ward-08-pu-013", code: "013", name: "NEW HOME MARKET UMUCHIGBO" },
      { id: "enugu-east-ward-08-pu-014", code: "014", name: "UKWUNGWU/ OGBODU VILLAGE SQUARE I" },
      { id: "enugu-east-ward-08-pu-015", code: "015", name: "OLD AIRPORT ROAD BY HARBARTEX JUNCTION DESTINY LAYOUT" },
      { id: "enugu-east-ward-08-pu-016", code: "016", name: "UGBO OKEKE SQUARE" },
      { id: "enugu-east-ward-08-pu-017", code: "017", name: "UKWUNGWU/OGBODU VILLAGE SQUARE II" },
      { id: "enugu-east-ward-08-pu-018", code: "018", name: "OGWUAGOR HEALTH CENTRE" },
      { id: "enugu-east-ward-08-pu-019", code: "019", name: "ST. JUDE PRIMARY SCHOOL ACADEMY ANIOMA LAYOUT" },
      { id: "enugu-east-ward-08-pu-020", code: "020", name: "UGWUORIE JUNCTION" },
      { id: "enugu-east-ward-08-pu-021", code: "021", name: "AMAOVULU VILLAGE SQUARE" },
    ],
  },

  // ============================================================
  // WARD 09 - TRANS-EKULU
  // ============================================================
  {
    id: "enugu-east-ward-09",
    code: "09",
    name: "TRANS-EKULU",
    pollingUnits: [
      { id: "enugu-east-ward-09-pu-001", code: "001", name: "OPEN SQUARE OPPOSITE ST. PHILIP I" },
      { id: "enugu-east-ward-09-pu-002", code: "002", name: "OPEN SQUARE OPPOSITE ST. PHILIP II" },
      { id: "enugu-east-ward-09-pu-003", code: "003", name: "OPEN SQUARE OPPOSITE ST. PHILIP III" },
      { id: "enugu-east-ward-09-pu-004", code: "004", name: "OPEN SQUARE OPPOSITE ST. PHILIP IV" },
      { id: "enugu-east-ward-09-pu-005", code: "005", name: "OPEN SQUARE OPPOSITE ST. PHILIP V" },
      { id: "enugu-east-ward-09-pu-006", code: "006", name: "OPEN SQUARE ALONG UMUDIOKA I" },
      { id: "enugu-east-ward-09-pu-007", code: "007", name: "OPEN SQUARE ALONG UMUDIOKA II" },
      { id: "enugu-east-ward-09-pu-008", code: "008", name: "OPEN SQUARE ALONG UMUDIOKA III" },
      { id: "enugu-east-ward-09-pu-009", code: "009", name: "TRANS EKULU PRIMARY SCHOOL I" },
      { id: "enugu-east-ward-09-pu-010", code: "010", name: "TRANS EKULU PRIMARY SCHOOL II" },
      { id: "enugu-east-ward-09-pu-011", code: "011", name: "TRANS EKULU PRIMARY SCHOOL III" },
      { id: "enugu-east-ward-09-pu-012", code: "012", name: "TRANS EKULU PRIMARY SCHOOL IV" },
      { id: "enugu-east-ward-09-pu-013", code: "013", name: "TRANS EKULU PRIMARY SCHOOL V" },
      { id: "enugu-east-ward-09-pu-014", code: "014", name: "UGBO ODOGWU PRIMARY SCHOOL I" },
      { id: "enugu-east-ward-09-pu-015", code: "015", name: "UGBO ODOGWU PRIMARY SCHOOL II" },
      { id: "enugu-east-ward-09-pu-016", code: "016", name: "UGBO ODOGWU PRIMARY SCHOOL III" },
      { id: "enugu-east-ward-09-pu-017", code: "017", name: "AGU OWA I" },
      { id: "enugu-east-ward-09-pu-018", code: "018", name: "AGU OWA II" },
      { id: "enugu-east-ward-09-pu-019", code: "019", name: "AGU OWA III" },
      { id: "enugu-east-ward-09-pu-020", code: "020", name: "AGU OWA IV" },
      { id: "enugu-east-ward-09-pu-021", code: "021", name: "AGU OWA V" },
      { id: "enugu-east-ward-09-pu-022", code: "022", name: "AGU ABOR HALL I" },
      { id: "enugu-east-ward-09-pu-023", code: "023", name: "AGU ABOR HALL II" },
      { id: "enugu-east-ward-09-pu-024", code: "024", name: "UGBO ODOGWU PRIMARY SCHOOL IV" },
      { id: "enugu-east-ward-09-pu-025", code: "025", name: "UGBO ODOGWU PRIMARY SCHOOL V" },
      { id: "enugu-east-ward-09-pu-026", code: "026", name: "SCHOOL OF DENTAL TECH. I" },
      { id: "enugu-east-ward-09-pu-027", code: "027", name: "SCHOOL OF DENTAL TECH. II" },
      { id: "enugu-east-ward-09-pu-028", code: "028", name: "TRANS EKULU PRIMARY SCHOOL VI" },
      { id: "enugu-east-ward-09-pu-029", code: "029", name: "AZIGBO LANE BY PENOKS BUS STOP" },
      { id: "enugu-east-ward-09-pu-030", code: "030", name: "POLE BUS STOP FEDERAL HOUSING TRANS EKULU ISUOFIA STREET" },
      { id: "enugu-east-ward-09-pu-031", code: "031", name: "OBIAJA STREET, POLE BUS STOP FEDERAL HOUSING" },
      { id: "enugu-east-ward-09-pu-032", code: "032", name: "IKPA OSINA JUNCTION" },
      { id: "enugu-east-ward-09-pu-033", code: "033", name: "UMUDIOKA BUS STOP FEDERAL HOUSING" },
      { id: "enugu-east-ward-09-pu-034", code: "034", name: "HILL VIEW TRANS – EKULU/BISHOP OTUBELU JUNIORATE" },
      { id: "enugu-east-ward-09-pu-035", code: "035", name: "MIKE TOREY AVENUE BY DAMIJA JUNCTION" },
      { id: "enugu-east-ward-09-pu-036", code: "036", name: "RCC ESTATE GATE EEDC" },
      { id: "enugu-east-ward-09-pu-037", code: "037", name: "OPEN SPACE ALONG MISSION ROAD BY DANDILAS GAS" },
      { id: "enugu-east-ward-09-pu-038", code: "038", name: "OGBANA OKWUTE MARKET UGBO ODOUGWU" },
      { id: "enugu-east-ward-09-pu-039", code: "039", name: "UGBO ODOUGWU ROAD BY MISSION ROAD" },
      { id: "enugu-east-ward-09-pu-040", code: "040", name: "CBN QUARTERS BUS STOP" },
      { id: "enugu-east-ward-09-pu-041", code: "041", name: "ENUGU ABOR STREET BY ROBAN STORES" },
      { id: "enugu-east-ward-09-pu-042", code: "042", name: "OPEN SPACE ALONG OJOTO CRESCENT" },
      { id: "enugu-east-ward-09-pu-043", code: "043", name: "ORIE ONUOGBA EZECHIME STREET BESIDES CBN QUARTERS" },
      { id: "enugu-east-ward-09-pu-044", code: "044", name: "HILL SIDE PRIMARY SCHOOL AGUABOR" },
      { id: "enugu-east-ward-09-pu-045", code: "045", name: "CHIGHA STREET BY ADIMORA JUNCTION" },
      { id: "enugu-east-ward-09-pu-046", code: "046", name: "UGBO OWA HEALTH CENTRE" },
      { id: "enugu-east-ward-09-pu-047", code: "047", name: "UGBO ENYI PHASE SIX EXTENSION/UGBOWA JUNCTION" },
      { id: "enugu-east-ward-09-pu-048", code: "048", name: "ABAKALIKI MARKET NEW GRA" },
      { id: "enugu-east-ward-09-pu-049", code: "049", name: "SANI ABACHA JUNCTION NEW GRA" },
      { id: "enugu-east-ward-09-pu-050", code: "050", name: "SHEKINA GLORY JUNCTION" },
      { id: "enugu-east-ward-09-pu-051", code: "051", name: "EKULU – GARDEN TANKER PARK" },
      { id: "enugu-east-ward-09-pu-052", code: "052", name: "EZIKE JUNCTION NEW GRA" },
      { id: "enugu-east-ward-09-pu-053", code: "053", name: "NIKE LAKE ROAD EZENWEREM STREET" },
      { id: "enugu-east-ward-09-pu-054", code: "054", name: "OPEN UNIVERSITY NIKE LAKE ROAD NEAR TRANSFORMER" },
    ],
  },

  // ============================================================
  // WARD 10 - IBAGWA-NIKE/EDEM
  // ============================================================
  {
    id: "enugu-east-ward-10",
    code: "10",
    name: "IBAGWA-NIKE/EDEM",
    pollingUnits: [
      { id: "enugu-east-ward-10-pu-001", code: "001", name: "IBAGWA NIKE SQUARE I" },
      { id: "enugu-east-ward-10-pu-002", code: "002", name: "IBAGWA NIKE SQUARE II" },
      { id: "enugu-east-ward-10-pu-003", code: "003", name: "EDEM VILLAGE SQUARE I" },
      { id: "enugu-east-ward-10-pu-004", code: "004", name: "EDEM VILLAGE SQUARE II" },
      { id: "enugu-east-ward-10-pu-005", code: "005", name: "AMAMKPUMA VILLAGE SQUARE" },
      { id: "enugu-east-ward-10-pu-006", code: "006", name: "IBAGWA NIKE SQUARE III" },
      { id: "enugu-east-ward-10-pu-007", code: "007", name: "IBAGWA NIKE SQUARE IV" },
      { id: "enugu-east-ward-10-pu-008", code: "008", name: "UGBO IYIOKU SQUARE" },
      { id: "enugu-east-ward-10-pu-009", code: "009", name: "UMUNONU VILLAGE SQUARE" },
      { id: "enugu-east-ward-10-pu-010", code: "010", name: "ONU ANI VILLAGE SQUARE" },
      { id: "enugu-east-ward-10-pu-011", code: "011", name: "OPEN SQUARE AGUOJA EDEM" },
      { id: "enugu-east-ward-10-pu-012", code: "012", name: "ONUUGWU EDEM VILLAGE" },
      { id: "enugu-east-ward-10-pu-013", code: "013", name: "OPEN SPACE OSHAGU" },
      { id: "enugu-east-ward-10-pu-014", code: "014", name: "OBINAGU VILLAGE SQUARE IBAGWA" },
    ],
  },

  // ============================================================
  // WARD 11 - UGWUGO NIKE
  // ============================================================
  {
    id: "enugu-east-ward-11",
    code: "11",
    name: "UGWUGO NIKE",
    pollingUnits: [
      { id: "enugu-east-ward-11-pu-001", code: "001", name: "C.P.S. UGWOGO I" },
      { id: "enugu-east-ward-11-pu-002", code: "002", name: "C.P.S. UGWOGO II" },
      { id: "enugu-east-ward-11-pu-003", code: "003", name: "C.P.S. UGWOGO III" },
      { id: "enugu-east-ward-11-pu-004", code: "004", name: "C.P.S. UGWOGO IV" },
      { id: "enugu-east-ward-11-pu-005", code: "005", name: "C.P.S. UGWOGO V" },
      { id: "enugu-east-ward-11-pu-006", code: "006", name: "C.P.S. UGWOGO VI" },
      { id: "enugu-east-ward-11-pu-007", code: "007", name: "C.P.S. UGWOGO VII" },
      { id: "enugu-east-ward-11-pu-008", code: "008", name: "AMAKPAKA HALL I" },
      { id: "enugu-east-ward-11-pu-009", code: "009", name: "AMAKPAKA HALL II" },
      { id: "enugu-east-ward-11-pu-010", code: "010", name: "AMAKPAKA HALL III" },
      { id: "enugu-east-ward-11-pu-011", code: "011", name: "C.P.S. UGWOGO VIII" },
    ],
  },

  // ============================================================
  // WARD 12 - MBULU-NJODO EAST
  // ============================================================
  {
    id: "enugu-east-ward-12",
    code: "12",
    name: "MBULU-NJODO EAST",
    pollingUnits: [
      { id: "enugu-east-ward-12-pu-001", code: "001", name: "AKPOGA TOWN HALL I" },
      { id: "enugu-east-ward-12-pu-002", code: "002", name: "AKPOGA TOWN HALL II" },
      { id: "enugu-east-ward-12-pu-003", code: "003", name: "AKPOGA TOWN HALL III" },
      { id: "enugu-east-ward-12-pu-004", code: "004", name: "NKOMORO ONUOGBA NIKE I" },
      { id: "enugu-east-ward-12-pu-005", code: "005", name: "NKOMORO ONUOGBA NIKE II" },
      { id: "enugu-east-ward-12-pu-006", code: "006", name: "C.P.S. AKPOGA I" },
      { id: "enugu-east-ward-12-pu-007", code: "007", name: "C.P.S. AKPOGA II" },
      { id: "enugu-east-ward-12-pu-008", code: "008", name: "C.P.S. AKPOGA III" },
      { id: "enugu-east-ward-12-pu-009", code: "009", name: "C.P.S. EZZA AKPOGA I" },
      { id: "enugu-east-ward-12-pu-010", code: "010", name: "C.P.S. EZZA AKPOGA II" },
      { id: "enugu-east-ward-12-pu-011", code: "011", name: "C.P.S. EZZA AKPOGA III" },
      { id: "enugu-east-ward-12-pu-012", code: "012", name: "CPS EZZA NKWUBO I" },
      { id: "enugu-east-ward-12-pu-013", code: "013", name: "CPS EZZA NKWUBO II" },
      { id: "enugu-east-ward-12-pu-014", code: "014", name: "CPS EZZA NKWUBO III" },
      { id: "enugu-east-ward-12-pu-015", code: "015", name: "NKWUBO TOWN SQUARE I" },
      { id: "enugu-east-ward-12-pu-016", code: "016", name: "NKWUBO TOWN SQUARE II" },
      { id: "enugu-east-ward-12-pu-017", code: "017", name: "UGWUOMU NIKE I" },
      { id: "enugu-east-ward-12-pu-018", code: "018", name: "UGWUOMU NIKE II" },
      { id: "enugu-east-ward-12-pu-019", code: "019", name: "UGWUOMU NIKE III" },
      { id: "enugu-east-ward-12-pu-020", code: "020", name: "OBINAGU UGWUOMU I" },
      { id: "enugu-east-ward-12-pu-021", code: "021", name: "OBINAGU UGWUOMU II" },
      { id: "enugu-east-ward-12-pu-022", code: "022", name: "ONUOGBA TOWN SQUARE I" },
      { id: "enugu-east-ward-12-pu-023", code: "023", name: "ONUOGBA TOWN SQUARE II" },
      { id: "enugu-east-ward-12-pu-024", code: "024", name: "AKPARATA VILLAGE SQUARE" },
      { id: "enugu-east-ward-12-pu-025", code: "025", name: "AKPUOGA HEALTH CENTRE" },
      { id: "enugu-east-ward-12-pu-026", code: "026", name: "NGAMGBO ASA SQUARE EZZA NKOMORO ONUOGBA NIKE" },
      { id: "enugu-east-ward-12-pu-027", code: "027", name: "NNPC DEPOT JUNCTION ONUOGBA" },
      { id: "enugu-east-ward-12-pu-028", code: "028", name: "14TH MILE EZIOBODO AKPUOGA NIKE" },
      { id: "enugu-east-ward-12-pu-029", code: "029", name: "13TH MILE AKPUOGA" },
      { id: "enugu-east-ward-12-pu-030", code: "030", name: "ORIE ENUOGBA MARKET" },
      { id: "enugu-east-ward-12-pu-031", code: "031", name: "ONUOGBA NIKE PRIMARY SCHOOL" },
    ],
  },
];